// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie.Infrastructure.Repositories;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movie.Infrastructure.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20260103150901_MoveSchema")]
    partial class MoveSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Movie")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Movie.Domain.Aggregate.Movie", b =>
                {
                    b.Property<long>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MovieId"));

                    b.Property<string>("MovieStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovieId");

                    b.ToTable("Movies", "Movie");
                });

            modelBuilder.Entity("Movie.Domain.Aggregate.Movie", b =>
                {
                    b.OwnsOne("Movie.Domain.Aggregate.MovieInfo", "MovieInfo", b1 =>
                        {
                            b1.Property<long>("MovieId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AdienceRating")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Director")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.PrimitiveCollection<string[]>("Genres")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<DateTime>("ReleaseDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("RuntimeMinutes")
                                .HasColumnType("integer");

                            b1.Property<string>("Synopsis")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MovieId");

                            b1.ToTable("Movies", "Movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");

                            b1.OwnsMany("Movie.Domain.Aggregate.Actor", "Casts", b2 =>
                                {
                                    b2.Property<long>("MovieInfoMovieId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<DateTime>("DateOfBirth")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("National")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Role")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("MovieInfoMovieId", "Id");

                                    b2.ToTable("Actor", "Movie");

                                    b2.WithOwner()
                                        .HasForeignKey("MovieInfoMovieId");
                                });

                            b1.Navigation("Casts");
                        });

                    b.Navigation("MovieInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
