// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using movie_shop_asp.Server.Infrastructure;

#nullable disable

namespace movie_shop_asp.Server.Migrations
{
    [DbContext(typeof(MovieShopContext))]
    [Migration("20260125111845_AddTheaterModule")]
    partial class AddTheaterModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Movie.Domain.Aggregate.Movie", b =>
                {
                    b.Property<long>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MovieId"));

                    b.Property<string>("MovieStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovieId");

                    b.ToTable("Movies", "Movie");
                });

            modelBuilder.Entity("Screening.Domain.Aggregate.MovieAggregate.Movie", b =>
                {
                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<string>("MovieStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovieId")
                        .HasName("PK_Movies1");

                    b.ToTable("Movies", "Screening");
                });

            modelBuilder.Entity("Screening.Domain.Aggregate.ScreenAggregate.Screen", b =>
                {
                    b.Property<long>("ScreenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScreenId"));

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SalesEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SalesStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TheaterId")
                        .HasColumnType("bigint");

                    b.HasKey("ScreenId");

                    b.HasIndex("MovieId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Screens", "Screening");
                });

            modelBuilder.Entity("Screening.Domain.Aggregate.TheaterAggregate.Theater", b =>
                {
                    b.Property<long>("TheaterId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("TheaterId");

                    b.ToTable("Theaters", "Screening");
                });

            modelBuilder.Entity("Theater.Domain.Aggregate.Theater", b =>
                {
                    b.Property<long>("TheaterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TheaterId"));

                    b.Property<int>("ColumnCount")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TheaterId")
                        .HasName("PK_Theaters1");

                    b.ToTable("Theaters", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Aggregate.Movie", b =>
                {
                    b.OwnsOne("Movie.Domain.Aggregate.MovieInfo", "MovieInfo", b1 =>
                        {
                            b1.Property<long>("MovieId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AdienceRating")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Director")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.PrimitiveCollection<string[]>("Genres")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<DateTime>("ReleaseDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("RuntimeMinutes")
                                .HasColumnType("integer");

                            b1.Property<string>("Synopsis")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MovieId");

                            b1.HasIndex("Title")
                                .IsUnique();

                            b1.ToTable("Movies", "Movie");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");

                            b1.OwnsMany("Movie.Domain.Aggregate.Actor", "Casts", b2 =>
                                {
                                    b2.Property<long>("MovieInfoMovieId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<DateTime>("DateOfBirth")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("National")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Role")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("MovieInfoMovieId", "Id");

                                    b2.ToTable("Actor", "Movie");

                                    b2.WithOwner()
                                        .HasForeignKey("MovieInfoMovieId");
                                });

                            b1.Navigation("Casts");
                        });

                    b.Navigation("MovieInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Screening.Domain.Aggregate.ScreenAggregate.Screen", b =>
                {
                    b.OwnsMany("Screening.Domain.Aggregate.ScreenAggregate.SeatHold", "SeatHolds", b1 =>
                        {
                            b1.Property<long>("ScreenId")
                                .HasColumnType("bigint");

                            b1.Property<string>("SeatCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<DateTimeOffset?>("HeldUntil")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("HoldToken")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ScreenId", "SeatCode");

                            b1.HasIndex("HoldToken");

                            b1.HasIndex("ScreenId", "Status");

                            b1.HasIndex("Status", "HeldUntil");

                            b1.ToTable("SeatHolds", "Screening");

                            b1.WithOwner()
                                .HasForeignKey("ScreenId");
                        });

                    b.Navigation("SeatHolds");
                });

            modelBuilder.Entity("Screening.Domain.Aggregate.TheaterAggregate.Theater", b =>
                {
                    b.OwnsMany("Screening.Domain.Aggregate.TheaterAggregate.TheaterSeat", "Seats", b1 =>
                        {
                            b1.Property<long>("TheaterId")
                                .HasColumnType("bigint");

                            b1.Property<string>("SeatCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.HasKey("TheaterId", "SeatCode");

                            b1.ToTable("TheaterSeats", "Screening");

                            b1.WithOwner()
                                .HasForeignKey("TheaterId");
                        });

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Theater.Domain.Aggregate.Theater", b =>
                {
                    b.OwnsMany("Theater.Domain.Aggregate.TheaterSeat", "Seats", b1 =>
                        {
                            b1.Property<long>("TheaterId")
                                .HasColumnType("bigint");

                            b1.Property<string>("SeatCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.HasKey("TheaterId", "SeatCode")
                                .HasName("PK_TheaterSeats1");

                            b1.ToTable("TheaterSeats", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TheaterId");
                        });

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
